---
- hosts: all
  sudo: true
  vars_files:
    - [ "vars/{{ ansible_os_family }}.yml" ]
  vars:
    oracle_java_set_as_default: yes
    jenkins_plugins:
      - git
      - ssh
      - workflow-aggregator
  roles:
    - { role: geerlingguy.java }
    - { role: ansiblebit.oracle-java }
    - { role: spantree.jenkins } # this is a fork of the role geerlingguy/jenkins
  tasks:
    - selinux: policy=targeted state=permissive
      when: ansible_os_family == "RedHat"

